server:
    port: 8006

spring:
    application:
        name: consul-provider-payment
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver #mysql驱动包
        url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
    #### consul注册中心地址
    cloud:
        consul:
            host: 192.168.138.100
            port: 8500
            discovery:
                service-name: ${spring.application.name}
                #health-check-url: http://${spring.cloud.consul.host}:${server.port}/actuator/health
                heartbeat:
                    enabled: true