server:
    port: 7001
eureka:
    instance:
        hostname: eureka7001.com #eureka服务端的实例名称
    client:
        register-with-eureka: false #false表示不向注册中心注册自己
        fetch-register: false        #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
        service-url:
            #defaultZone: http://eureka7002.com:7002/eureka/ #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址，集群使用其它地址，单机版是自己
            defaultZone: http://eureka7001.com:7001/eureka/
    server:
        enable-self-preservation: false #关闭自我保护机制，保证服务不可用的时候被及时剔除
        eviction-interval-timer-in-ms: 2000 #2s钟 # 清理间隔（单位毫秒，默认是60*1000）启用主动失效，并且每次主动失效检测间隔为2s，
        # Eureka Server会定时（间隔值是eureka.server.eviction-interval-timer-in-ms，默认值为0，默认情况不删除实例）进行检查，
        # 如果发现实例在在一定时间（此值由客户端设置的eureka.instance.lease-expiration-duration-in-seconds定义，默认值为90s）内没有收到心跳，则会注销此实例。