server:
    port: 83
spring:
    application:
        name: nacos-consumer
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
#消费者要去访问的微服务名称（注册进nacos的微服务提供者）,可配可不配
service-url:
    nacos-user-service: http://nacos-provider